import type { Metadata } from "next";
import { Gantari } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const celliad = localFont({
  src: "./fonts/Celliad.woff",
  weight: "100 900",
  variable: "--font-celliad",
});

const excali = localFont({
  src: "./fonts/Virgil.woff2",
  weight: "100 900",
  variable: "--font-excali",
});

const gantari = Gantari({
  variable: "--font-gantari",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gantari.variable} ${excali.variable} ${celliad.variable} antialiased`}
      >
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
