export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FALIURE = 'USER_SIGNIN_FALIURE';
export const USER_PROFILE_UPDATE = 'USER_PROFILE_UPDATE';
export const LOGOUT = 'LOGOUT';